### PR TITLE
fix: incorrect deprecation warning when the plugin doesn't exist

### LINKED ISSUE #2415: Wrong error message when a plugin in package.toml but not exists in plugins folder
### What system are you running Yazi on?

Linux Wayland

### What terminal are you running Yazi in?

wezterm 20250223-153857-fd532a8c

### `yazi --debug` output

```Shell
❯ yazi --debug

Yazi
    Version: 25.2.26 (f80446fb 2025-02-27)
    Debug  : false
    Triple : x86_64-unknown-linux-gnu (linux-x86_64)
    Rustc  : 1.85.0 (4d91de4e 2025-02-17)

Ya
    Version: 25.2.26 (f80446fb 2025-02-27)

Emulator
    TERM                : Some("xterm-256color")
    TERM_PROGRAM        : Some("WezTerm")
    TERM_PROGRAM_VERSION: Some("20250223-153857-fd532a8c")
    Brand.from_env      : Some(WezTerm)
    Emulator.detect     : Emulator { kind: Left(WezTerm), light: false, cell_size: Some((16, 36)) }

Adapter
    Adapter.matches: Iip

Desktop
    XDG_SESSION_TYPE           : Some("wayland")
    WAYLAND_DISPLAY            : Some("wayland-1")
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: Some("882f7ad7d2bbfc7440d0ccaef93b1cdd78e8e3ff_1740619561_1813804682")
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL           : Some("/usr/bin/zsh")
    EDITOR          : Some("lvim")
    VISUAL          : Some("lvim")
    YAZI_FILE_ONE   : None
    YAZI_CONFIG_HOME: None
    YAZI_ZOXIDE_OPTS: None
    FZF_DEFAULT_OPTS: Some("--ansi --height=100% --reverse --cycle")

Text Opener
    default     : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-create: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block-rename: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : No such file or directory (os error 2)
    tmux build flags   : enable-sixel=Unknown
    ZELLIJ_SESSION_NAME: None
    Zellij version     : 0.41.2

Dependencies
    file          : 5.46
    ueberzugpp    : No such file or directory (os error 2)
    ffmpeg/ffprobe: 7.1 / ffprobe version N-116914-g8a314e3f11 Copyright (c) 2007-2024 the FFmpeg developers
    pdftoppm      : 25.02.0
    magick        : 7.1.1-44
    fzf           : 0.60.2
    fd/fdfind     : 10.2.0 / No such file or directory (os error 2)
    rg            : 14.1.1
    chafa         : 1.14.5
    zoxide        : 0.9.7
    7zz/7z        : No such file or directory (os error 2) / 24.09
    jq            : 1.7.1

Clipboard
    wl-copy/paste: 2.2.1 / 2.2.1
    xclip        : No such file or directory (os error 2)
    xsel         : No such file or directory (os error 2)


See https://yazi-rs.github.io/docs/plugins/overview#debugging on how to enable logging or debug runtime errors.
```

### Describe the bug

use `ya pack -a` a plugin, delete it from plugins folder, then enter `yazi`, the deprecated entry file warning shows,

Image

It should be some like 'The plugin xxx is not exist Please check and install first'

### Minimal reproducer

use `ya pack -a` a plugin, delete it from plugins folder, then enter `yazi`

### Anything else?

_No response_

### Checklist

- [x] I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#binaries), and the issue is still reproducible
- [x] I updated the debug information (`yazi --debug`) input box to the nightly that I tried
- [ ] I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)

### PR DESCRIPTION
**Pull request by hankertrix**
Fixes #2415.

### CODE REVIEW

File: yazi-plugin/src/loader/loader.rs [hunk 1]
```diff
@@ -20,7 +20,9 @@ impl Deref for Loader {
 	type Target = RwLock<HashMap<String, Chunk>>;
 
 	#[inline]
-	fn deref(&self) -> &Self::Target { &self.cache }
+	fn deref(&self) -> &Self::Target {
```
Comment (sxyazi) [inline yazi-plugin/src/loader/loader.rs:23]: Please keep the original style here

**Review by sxyazi — CHANGES_REQUESTED** [review]

**Comment by hankertrix** [comment]
You're welcome!
